# setting variables for APP
auth:

  # SET_YOUR_JWT_INFO_HERE
  jwt:
    expiry: "240"                 # <-- the number means in minutes
    secret: "supersecretpassword" # <-- Don't forget to change this to your own!